export const CourseCategories = [
  // Academic Subjects
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "History",
  "Geography",
  "Political Science",
  "Economics",
  "Psychology",
  "Sociology",
  "Philosophy",
  "Environmental Science",
  "Statistics",
  "Literature",
  "Language Learning",

  // Technology & Programming
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cybersecurity",
  "Cloud Computing",
  "DevOps",
  "Blockchain",
  "UI/UX Design",
  "Software Engineering",

  // Creative & Design
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Animation",
  "Music Theory",
  "Music Production",
  "Painting & Drawing",
  "3D Modeling",

  // Professional & Career Skills
  "Business & Management",
  "Marketing",
  "Entrepreneurship",
  "Finance",
  "Accounting",
  "Sales",
  "Leadership",
  "Project Management",
  "Human Resources",
  "Negotiation",
  "Resume Writing",
  "Interview Preparation",
  "Public Speaking",

  // Personal Development
  "Productivity",
  "Time Management",
  "Mindfulness & Meditation",
  "Mental Health",
  "Communication Skills",
  "Critical Thinking",
  "Goal Setting",

  // Test Prep
  "SAT",
  "ACT",
  "GRE",
  "GMAT",
  "IELTS",
  "TOEFL",
  "UPSC",
  "NEET",
  "JEE",
  "GATE",
  "CAT",

  // Language & Communication
  "English Language",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Sign Language",
  "Writing & Grammar",

  // Vocational & Trade Skills
  "Carpentry",
  "Plumbing",
  "Electrical Engineering",
  "Automotive Repair",
  "Fashion Design",
  "Culinary Arts",
  "Hospitality",
  "Mechanics",

  // Health & Science
  "Nutrition",
  "Medicine",
  "Nursing",
  "Anatomy",
  "Pharmacology",
  "Yoga & Fitness",
  "First Aid",

  // Kids & School Education
  "Early Learning",
  "Elementary School",
  "Middle School",
  "High School",
  "STEM for Kids",

  // Life Skills
  "Financial Literacy",
  "Cooking",
  "Home Organization",
  "Gardening",
  "Self-defense",

  // Miscellaneous
  "Ethics",
  "Law",
  "Religion & Theology",
  "Cultural Studies",
  "Current Affairs",
  "Astronomy",
  "Meteorology",
];
